<div class="container-fluid">
    <div class="row">
        <center><h4><i><?= $SalaChat; ?></i></h4></center>
    </div>
    <div class="row">
        <div class="col-12 col-sm-1 col-md-2 col-lg-2 col-xl-2"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-8 col-xl-8 shadow border">
            <div class="CajaChat border my-2">

            </div>
            <form action="" method="post">
                <input type="text" name="chatId" id="chatId" value="<?= $SalaChat; ?>" class="form-control" readonly>
                <textarea name="" id="" cols="30" rows="2" class="form-control" placeholder="Enviar Mensaje"></textarea>
                <input type="submit" value="Enviar" class="btn btn-outline-success my-2">
            </form>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-2 col-xl-2"></div>
    </div>
</div>