<div class="container-fluid">
    <div class="row mb-3">
        <div class="col-12 col-sm-1 col-md-2 col-lg-2 col-xl-2"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-8 col-xl-8">
            <div class="container-fluid">
                <div class="row border shadow">
                    <div class="col-2 text-start">
                        <img src="<?php if ($image['image'] != null){ echo $image['image'];}else{echo 'app\master\views\assets\css\images\sinfoto.webp';} ?>" class="rounded-circle img-thumbnail" style="width:65px;height: auto; " alt="<?= $SalaChat; ?>">
                    </div>
                    <div class="col-10 text-start mt-3">
                        <h4><i><?= $SalaChat; ?></i></h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-2 col-xl-2"></div>
    </div>
</div>
<div class="row mb-5">
    <div class="col-12 col-sm-1 col-md-2 col-lg-2 col-xl-2"></div>
    <div class="col-12 col-sm-10 col-md-8 col-lg-8 col-xl-8 shadow border">
        <div class="CajaChat border my-2">

        </div>

        <form action="" method="post">
            <input type="text" name="chatId" id="chatId" value="<?= $SalaChat; ?>" class="form-control" readonly>
            <div class="emoji-picker-container">
                <textarea class="form-control" cols="30" rows="1" data-emojiable="true" data-emoji-input="unicode" type="text" name="" id="" placeholder="Enviar Mensaje"></textarea>
            </div>
            <button class="btn btn-outline-success my-2"><i class="far fa-paper-plane fa-2x"></i></button>
        </form>
    </div>
    <div class="col-12 col-sm-1 col-md-2 col-lg-2 col-xl-2"></div>
</div>

</div>