<form action="" method="post">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3"></div>
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-6 text-center shadow border">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Seleccionar</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Usuario</th>
                        </tr>
                    </thead>
                    <tbody id="TablaTransferirChat">

                    </tbody>
                </table>
            </div>
            <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3"></div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3"></div>
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-6 my-4">
                <label for="SeleccionSalaChat">Seleccione Conversacion:</label>
                <select name="SeleccionSalaChat" id="SeleccionSalaChat" class="form-select form-select-sm">
                    
                </select>
            </div>
            <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3"></div>
        </div>
    </div>
</form>