<form action="" method="post">
    <div class="container-fluid">
        <div class="row my-3">
            <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-4"></div>
            <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                <center><h2><i>Transferir Sala de chat</i></h2></center>
            </div>
            <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-4"></div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3"></div>
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-6 text-center shadow border">
                <table class="table table-hover"  id="TablaTransferirChat">
                    <thead>
                        <tr>
                            <th>Seleccionar</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Usuario</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3"></div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3"></div>
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-6 border shadow my-4">
                <label for="SeleccionSalaChat">Seleccione Conversacion:</label>
                <select name="SeleccionSalaChat" id="SeleccionSalaChat" class="form-select form-select-sm my-2">

                </select>
            </div>
            <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-3">
            <button class="btn btn-outline-success my-5">Transferir</button>
            </div>
        </div>
    </div>
</form>