<div class="container-fluid  ml-5">
    <div class="row">
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4 text-center">
            <h2><i>Dashboard</i></h2>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-1 col-md-1 col-lg-1 col-xl-1"></div>
        <div class="col-12 col-sm-10 col-md-10 col-lg-10 col-xl-10">
            <!-- Agregando Campos -->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
                        <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                            <div class="card-header"><i class="far fa-comments fa-4x"></i></div>
                            <div class="card-body">
                                <h5 class="card-title">Pendientes</h5>
                                <p class="card-text" id="CardSalasPendientes"></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
                        <div class="card text-white bg-warning mb-3" style="max-width: 18rem;">
                            <div class="card-header"><i class="far fa-comment-alt fa-4x"></i></div>
                            <div class="card-body">
                                <h5 class="card-title">Abiertos</h5>
                                <p class="card-text" id="CardSalasAbiertas"></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
                        <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                            <div class="card-header"><i class="far fa-user fa-4x"></i></div>
                            <div class="card-body">
                                <h5 class="card-title">Asignados</h5>
                                <p class="card-text" id="CardSalasAsignadas"></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
                    <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
                            <div class="card-header"><i class="far fa-comment fa-4x"></i></div>
                            <div class="card-body">
                                <h5 class="card-title">en Seguimiento</h5>
                                <p class="card-text" id="CardSalasAsignadas">//</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-1 col-md-1 col-lg-1 col-xl-1"></div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-1 col-md-2 col-lg-3"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 border shadow">
            <table id="TableDasboard" class="table table-hover text-center">
                <thead>
                    <tr>
                        <th>
                            Nombre
                        </th>
                        <th>
                            Apellido
                        </th>
                        <th>
                            usuario
                        </th>
                        <th>
                            Chat Pendientes
                        </th>
                        <th>
                            Chat Seguimiento
                        </th>
                    </tr>
                </thead>
                <tbody id="ChatAsignadosAgentes">

                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-3"></div>
    </div>
</div>