<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4 text-center">
            <h2><i>Dashboard</i></h2>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-3 col-xl-4"></div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-1 col-md-1 col-lg-1 col-xl-1"></div>
        <div class="col-12 col-sm-10 col-md-10 col-lg-10 col-xl-10 border">
            <!-- Agregando Campos -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2">
                        <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                            <div class="card-header"><i class="far fa-comments fa-4x"></i></div>
                            <div class="card-body">
                                <h5 class="card-title">Salas Pendientes</h5>
                                <p class="card-text"><?= $conteo ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
                    <div class="col-2 col-sm-2 col-md-2 col-lg-2 col-xl-2"></div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-1 col-md-1 col-lg-1 col-xl-1"></div>
    </div>
    <div class="row">
        <table id="TableDasboard">
            <thead>
                <tr>
                    <th>
                        Agentes
                    </th>
                    <th>
                        Chat Activos
                    </th>
                    <th>
                        Chat Pendientes
                    </th>
                    <th>
                        Chat Seguimiento
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>