<div class="container-fluid ml-5">
    <div class="row mb-3">
        <div class="col-12 col-sm-1 col-md-2 col-lg-2 col-xl-2"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-8 col-xl-8">
            <div class="container-fluid">
                <div class="row border shadow">
                    <div class="col-2 text-start">
                        <img src="<?php if ($image['image'] != null) {
                                        echo $image['image'];
                                    } else {
                                        echo 'app\admin\views\assets\css\images\sinfoto.webp';
                                    } ?>" class="rounded-circle img-thumbnail" style="width:65px;height: auto; " alt="<?= $SalaChat; ?>">
                    </div>
                    <div class="col-10 text-start mt-3">
                        <h4><i><?= $SalaChat; ?></i></h4>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-2 col-xl-2 mt-3">
            <form action="Inicio" method="POST">
                <button class="btn btn-outline-danger" value="<?= $SalaChat; ?>" name="btnCerrarChat" type="submit">Cerrar Chat</button>
            </form>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-12 col-sm-1 col-md-2 col-lg-2 col-xl-2"></div>
        <div class="col-12 col-sm-10 col-md-8 col-lg-8 col-xl-8 shadow border">
            <div class="CajaChat border my-2 bg-light" id="datos_chat">



            </div>
            <form id="frmMostrarChat">
                <div class="container-fluid my-2">
                    <div class="row">
                        <div class="col-12 col-sm-11 col-md-11 col-lg-11 col-xl-11">
                            <input type="text" name="chatId" id="chatId" value="<?= $SalaChat; ?>" class="form-control" readonly>
                            <div class="emoji-picker-container mt-2">
                                <!--<input class="form-control" data-emojiable="true" data-emoji-input="unicode" type="text" name="txtCuerpoMensage" id="txtCuerpoMensage" placeholder="Enviar Mensaje">-->
                                <input class="form-control" maxlength="60" type="text" autocomplete="off" name="txtCuerpoMensage" id="txtCuerpoMensage" placeholder="Enviar Mensaje">
                                <p id="CantidadCaracteresMaximos" class="help-block"></p>
                            </div>
                        </div>
                        <div class="col-12 col-sm-1 col-md-1 col-lg-1 col-xl-1 mt-3">
                            <button class="btn btn-outline-success" id="btnEnviarMensajeWhatsapp"><i class="far fa-paper-plane fa-1x"></i></button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-12 col-sm-1 col-md-2 col-lg-2 col-xl-2"></div>
    </div>
</div>